version: '2'

services:
  icecast:
    image: vitiman/alpine-icecast:latest
    container_name: icecast
    ports:
      - "8000:8000"
    networks:
      - music_stack

  # Add your host volumen in path/to/... or add your own volume below
  mpd:
    image: vitiman/alpine-mpd:latest
    container_name: mpd
    ports:
      - "6600:6600"
    depends_on:
      - icecast
    networks:
      - music_stack
    volumes:
      - /home/mark/Music:/var/lib/mpd/music
      - ./playlists:/var/lib/mpd/playlists
      - ./data:/var/lib/mpd/database

  sima:
    image: vitiman/alpine-sima:latest
    container_name: sima
    depends_on:
      - mpd
    networks:
      - music_stack

  ympd:
    image: vitiman/alpine-ympd:latest
    container_name: ympd
    ports:
      - "8080:8080"
    depends_on:
      - mpd
    networks:
      - music_stack

networks:
  music_stack:
    driver: bridge

# If you use your own volumes instead host volumes, uncomment this section
# volumes:
#   mpd_music:
#     external: true
#   mpd_playlists:
#     external: true
#   mpd_database:
#     external: true


