version: '3'

services:
  ui:
    image: ghcr.io/mark-me/boelmuziek-ui:v0.0.1
    container_name: ui
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    depends_on:
      - icecast
      - mpd
    ports:
      - 80:80
    networks:
      - music_stack
  controller:
    image: ghcr.io/mark-me/boelmuziek-controller:v0.0.1
    container_name: controller
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    depends_on:
      - mpd
    ports:
      - 5000:5000
    networks:
      - music_stack
  icecast:
    image: ghcr.io/mark-me/boelmuziek-icecast:v0.0.1
    container_name: icecast
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 8000:8000
    networks:
      - music_stack
  mpd:
    image: ghcr.io/mark-me/boelmuziek-mpd:v0.0.1
    container_name: mpd
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 6600:6600
    networks:
      - music_stack
    volumes:
      - ${DIR_MUSIC}:/var/lib/mpd/music
      - ${DIR_MPD_PLAYLIST}:/var/lib/mpd/playlists
      - ${DIR_MPD_DB}:/var/lib/mpd/database
      - ${DIR_MPD_STATE}:/var/lib/mpd/state
  snapserver:
    image: ghcr.io/mark-me/boelmuziek-snapserver:v0.0.1
    container_name: snapserver
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    depends_on:
      - mpd
    ports:
      - 1704:1704
      - 1705:1705
    volumes:
        - ${DIR_MPD_STATE}/snapfifo:/var/lib/snapserver/soundshare/snapfifo:rw'
    networks:
      - music_stack

networks:
  music_stack:
    driver: bridge

