version: '3'

services:
  ui:
    image: ghcr.io/mark-me/boelmuziek-ui:v0.0.1
    container_name: ui
    restart: unless-stopped
    depends_on:
      - icecast
      - mpd
    ports:
      - 80:80
    networks:
      - music_stack
  icecast:
    image: ghcr.io/mark-me/boelmuziek-icecast:v0.0.1
    container_name: icecast
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - music_stack
  mpd:
    image: ghcr.io/mark-me/boelmuziek-mpd:v0.0.1
    container_name: mpd
    restart: unless-stopped
    depends_on:
      - icecast
    ports:
      - 6600:6600
    networks:
      - music_stack
    volumes:
      - music:/var/lib/mpd/music
      - playlists:/var/lib/mpd/playlists
      - db:/var/lib/mpd/database
  snapserver:
    image: ghcr.io/mark-me/boelmuziek-snapserver:v0.0.1
    container_name: snapserver
    restart: unless-stopped
    depends_on:
      - mpd
    ports:
      - 1704:1704
    volumes:
        - '${PWD}/mpdstate/snapfifo:/var/lib/snapserver/soundshare/snapfifo:rw'
        - '${PWD}/snapserver/snapserver.conf:/var/lib/snapserver/snapserver.conf:ro'
    networks:
      - music_stack

networks:
  music_stack:
    driver: bridge

volumes:
  music:
    driver: local
    driver_opts:
      type: none
      device: /home/mark/Music
      o: "bind,ro"
  playlists:
    driver: local
    driver_opts:
      type: none
      device: /home/mark/Development/boelmuziek-data/playlists
      o: "bind,rw"
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/mark/Development/boelmuziek-data/db
      o: "bind,rw"
  snapserver:
    driver: local
    driver_opts:
      type: none
      device: /home/mark/Development/boelmuziek-data/snapserver
      o: "bind,rw"

