version: '3'

services:
  icecast:
    image: ghcr.io/mark-me/boelmuziek-icecast:v0.0.1
    container_name: icecast
    ports:
      - 8000:8000
    networks:
      - music_stack
  mpd:
    image: ghcr.io/mark-me/boelmuziek-mpd:v0.0.1
    container_name: mpd
    ports:
      - 6600:6600
    depends_on:
      - icecast
    networks:
      - music_stack
    volumes:
      - music:/var/lib/mpd/music
      - playlist:/var/lib/mpd/playlists
      - db:/var/lib/mpd/database
  snapserver:
    image: ghcr.io/mark-me/boelmuziek-snapserver:v0.0.1
    container_name: snapserver
    ports:
      - 1704:1704
    depends_on:
      - snapserver
    volumes:
        - '${PWD}/mpdstate/snapfifo:/var/lib/snapserver/soundshare/snapfifo:rw'
        - '${PWD}/snapserver/snapserver.conf:/var/lib/snapserver/snapserver.conf:ro'

networks:
  music_stack:
    driver: bridge

volumes:
  music:
    driver: local
    driver_opts:
      type: none
      device: /home/mark/Music
      o: "bind,ro"
  playlist:
    driver: local
    driver_opts:
      type: none
      device: /home/mark/Development/boelmuziek-data/playlist
      o: "bind,rw"
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/mark/Development/boelmuziek-data/db
      o: "bind,rw"
  snapserver:
    driver: local
    driver_opts:
      type: none
      device: /home/mark/Development/boelmuziek-data/snapserver
      o: "bind,rw"

