version: '3'

services:
  ui:
    image: ghcr.io/mark-me/boelmuziek-ui:${TAG_UI}
    container_name: ui
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    depends_on:
      - icecast
      - mpd
    ports:
      - 80:80
    networks:
      - music_stack
  ympd:
    image: ghcr.io/mark-me/boelmuziek-ympd:${TAG_YMPD}
    container_name: ympd
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    depends_on:
      - mpd
    ports:
      - 8080:8080
    networks:
      - music_stack
  controller:
    image: ghcr.io/mark-me/boelmuziek-controller:${TAG_CONTROLLER}
    container_name: controller
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    depends_on:
      - mpd
    ports:
      - 5000:5000
    networks:
      - music_stack
    volumes:
      - ${DIR_CONTROLLER_CONFIG}:/app/config
  icecast:
    image: ghcr.io/mark-me/boelmuziek-icecast:${TAG_ICECAST}
    container_name: icecast
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 8000:8000
    networks:
      - music_stack
  mpd:
    image: ghcr.io/mark-me/boelmuziek-mpd:${TAG_MPD}
    container_name: mpd
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 6600:6600
    networks:
      - music_stack
    volumes:
      - ${DIR_MUSIC}:/var/lib/mpd/music:ro
      - ${DIR_MPD_PLAYLISTS}:/var/lib/mpd/playlists
      - ${DIR_MPD_DB}:/var/lib/mpd/database
      - ${DIR_MPD_STATE}:/var/lib/mpd/state/:rw
      - ./mpd/mpdscribble.conf:/etc/mpdscribble.conf
  snapserver:
    image: ghcr.io/mark-me/boelmuziek-snapserver:${TAG_SNAPSERVER}
    container_name: snapserver
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    depends_on:
      - mpd
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780
    volumes:
        - ${DIR_MPD_STATE}/snapfifo:/var/lib/snapserver/soundshare/snapfifo:rw'
    networks:
      - music_stack

networks:
  music_stack:
    driver: bridge

